# Build using 64-bit Windows.
os: unstable
platform: x64

# Because of this:
#   https://help.github.com/articles/dealing-with-line-endings/
init:
- git config --global core.autocrlf input

install:
# Install/switch to node 7 for x64.
- ps: Install-Product node LTS x64
# Update global npm install.
- npm install npm -g
# Install app dependencies.
- npm i


# Only build on tags.
skip_non_tags: true

# Download repo as a zip file.
shallow_clone: true

# Only clone the 3 latest commits.
clone_depth: 3


# Cache some dirs for faster build.
cache:
#  - node_modules
#  - app/node_modules


# Quiet-ish build.
build:
  verbosity: minimal


# The executable(s) expected.
artifacts:
  # Path to artifact
- path: dist/*.exe
  # Assign a unique name to it.
  name: reliefvalve

# ...
build_script:
- npm run dist-32

# ...
test: off

# Deploy to GitHub Releases
deploy:
  provider: GitHub
  # This is mine, get your own!
  #  Needed to access GH API.
  auth_token:
    secure: yc7IkqH7Sgpc9AaumTPtZXlpbPde5huW9CK9YoMqWYxIND1yrEzQeole585FKcWr
  # Refer to artifact by set name.
  artifact: reliefvalve
  # Do not create a draft.
  draft: false
  # Do not create a prerelease
  prerelease: false
  on:
    # Only deploy from a tag.
    appveyor_repo_tag: true
